import React, { createContext, useContext, useState } from 'react';

const AppContext = createContext();

export const useApp = () => {
  const context = useContext(AppContext);
  if (!context) {
    throw new Error('useApp must be used within AppProvider');
  }
  return context;
};

export const AppProvider = ({ children }) => {
  const [categories, setCategories] = useState([
    { id: 1, name: 'Fruits', description: 'Fruits frais', color: '#ff6b6b' },
    { id: 2, name: 'Légumes', description: 'Légumes frais', color: '#4ecdc4' },
    { id: 3, name: 'Boissons', description: 'Boissons diverses', color: '#45b7d1' },
    { id: 4, name: 'Confiserie', description: 'Produits sucrés', color: '#e74c3c' },
    { id: 5, name: 'Produits laitiers', description: 'Lait, fromage, yaourt', color: '#f39c12' },
    { id: 6, name: 'Boulangerie', description: 'Pain et pâtisseries', color: '#d35400' },
    { id: 7, name: 'Épicerie', description: 'Produits de base', color: '#8e44ad' },
  ]);

  const [labels, setLabels] = useState([
    {
      id: 1,
      name: 'Kinder Bueno',
      price: '2.00',
      quantity: '35.00',
      pricePerUnit: '57.14',
      barcode: '1234567890123',
      categoryId: 4,
      description: 'Barre chocolatée',
      createdAt: new Date().toISOString(),
      unit: 'pc',
    },
    {
      id: 2,
      name: 'Pommes Golden',
      price: '3.50',
      quantity: '1.00',
      pricePerUnit: '3.50',
      barcode: '2345678901234',
      categoryId: 1,
      description: 'Pommes golden délicieuses',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 3,
      name: 'Coca-Cola 1.5L',
      price: '2.20',
      quantity: '1.50',
      pricePerUnit: '1.47',
      barcode: '3456789012345',
      categoryId: 3,
      description: 'Boisson gazeuse cola',
      createdAt: new Date().toISOString(),
      unit: 'L',
    },
    {
      id: 4,
      name: 'Tomates cerises',
      price: '4.20',
      quantity: '0.50',
      pricePerUnit: '8.40',
      barcode: '4567890123456',
      categoryId: 2,
      description: 'Tomates cerises bio',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 5,
      name: 'Yaourt nature Danone',
      price: '3.80',
      quantity: '4.00',
      pricePerUnit: '0.95',
      barcode: '5678901234567',
      categoryId: 5,
      description: 'Yaourt nature pack de 4',
      createdAt: new Date().toISOString(),
      unit: 'pc',
    },
    {
      id: 6,
      name: 'Baguette tradition',
      price: '1.20',
      quantity: '1.00',
      pricePerUnit: '1.20',
      barcode: '6789012345678',
      categoryId: 6,
      description: 'Pain baguette tradition',
      createdAt: new Date().toISOString(),
      unit: 'pc',
    },
    {
      id: 7,
      name: 'Pâtes Barilla',
      price: '1.85',
      quantity: '0.50',
      pricePerUnit: '3.70',
      barcode: '7890123456789',
      categoryId: 7,
      description: 'Pâtes spaghetti 500g',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 8,
      name: 'Bananes',
      price: '2.30',
      quantity: '1.20',
      pricePerUnit: '1.92',
      barcode: '8901234567890',
      categoryId: 1,
      description: 'Bananes équitables',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 9,
      name: 'Nutella 400g',
      price: '4.50',
      quantity: '0.40',
      pricePerUnit: '11.25',
      barcode: '9012345678901',
      categoryId: 4,
      description: 'Pâte à tartiner noisette-cacao',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 10,
      name: 'Eau minérale Evian',
      price: '1.80',
      quantity: '1.50',
      pricePerUnit: '1.20',
      barcode: '0123456789012',
      categoryId: 3,
      description: 'Eau minérale naturelle',
      createdAt: new Date().toISOString(),
      unit: 'L',
    },
    {
      id: 11,
      name: 'Carottes bio',
      price: '2.80',
      quantity: '1.00',
      pricePerUnit: '2.80',
      barcode: '1357924680135',
      categoryId: 2,
      description: 'Carottes biologiques',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 12,
      name: 'Fromage Camembert',
      price: '3.20',
      quantity: '0.25',
      pricePerUnit: '12.80',
      barcode: '2468013579246',
      categoryId: 5,
      description: 'Camembert de Normandie',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 13,
      name: 'Croissants x6',
      price: '2.90',
      quantity: '6.00',
      pricePerUnit: '0.48',
      barcode: '3691470258369',
      categoryId: 6,
      description: 'Croissants pur beurre',
      createdAt: new Date().toISOString(),
      unit: 'pc',
    },
    {
      id: 14,
      name: 'Riz basmati',
      price: '3.40',
      quantity: '1.00',
      pricePerUnit: '3.40',
      barcode: '1472583690147',
      categoryId: 7,
      description: 'Riz basmati 1kg',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 15,
      name: 'Oranges',
      price: '2.80',
      quantity: '1.50',
      pricePerUnit: '1.87',
      barcode: '2583691470258',
      categoryId: 1,
      description: 'Oranges à jus',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 16,
      name: 'Haribo Dragibus',
      price: '1.60',
      quantity: '0.30',
      pricePerUnit: '5.33',
      barcode: '3692581470369',
      categoryId: 4,
      description: 'Bonbons dragibus colorés',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 17,
      name: 'Jus d\'orange Tropicana',
      price: '2.70',
      quantity: '1.00',
      pricePerUnit: '2.70',
      barcode: '1478520369147',
      categoryId: 3,
      description: 'Jus d\'orange 100% pur jus',
      createdAt: new Date().toISOString(),
      unit: 'L',
    },
    {
      id: 18,
      name: 'Courgettes',
      price: '2.40',
      quantity: '0.80',
      pricePerUnit: '3.00',
      barcode: '2581470369258',
      categoryId: 2,
      description: 'Courgettes fraîches',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 19,
      name: 'Lait demi-écrémé',
      price: '1.40',
      quantity: '1.00',
      pricePerUnit: '1.40',
      barcode: '3690258147036',
      categoryId: 5,
      description: 'Lait UHT demi-écrémé',
      createdAt: new Date().toISOString(),
      unit: 'L',
    },
    {
      id: 20,
      name: 'Pain de mie',
      price: '1.80',
      quantity: '0.50',
      pricePerUnit: '3.60',
      barcode: '1470369258147',
      categoryId: 6,
      description: 'Pain de mie complet',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 21,
      name: 'Huile d\'olive',
      price: '5.20',
      quantity: '0.50',
      pricePerUnit: '10.40',
      barcode: '2580369147258',
      categoryId: 7,
      description: 'Huile d\'olive extra vierge',
      createdAt: new Date().toISOString(),
      unit: 'L',
    },
    {
      id: 22,
      name: 'Saumon fumé',
      price: '12.50',
      quantity: '0.15',
      pricePerUnit: '83.33',
      barcode: '3691470258147',
      categoryId: 5,
      description: 'Saumon fumé d\'Écosse',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 23,
      name: 'Chips Lay\'s',
      price: '2.10',
      quantity: '0.13',
      pricePerUnit: '16.15',
      barcode: '1470258369147',
      categoryId: 7,
      description: 'Chips nature 130g',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 24,
      name: 'Mangue',
      price: '3.80',
      quantity: '0.45',
      pricePerUnit: '8.44',
      barcode: '2581470369147',
      categoryId: 1,
      description: 'Mangue tropicale',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 25,
      name: 'Bière Heineken',
      price: '4.20',
      quantity: '0.33',
      pricePerUnit: '12.73',
      barcode: '3690147258369',
      categoryId: 3,
      description: 'Bière blonde 33cl',
      createdAt: new Date().toISOString(),
      unit: 'L',
    },
    {
      id: 26,
      name: 'Épinards frais',
      price: '2.60',
      quantity: '0.25',
      pricePerUnit: '10.40',
      barcode: '1472580369147',
      categoryId: 2,
      description: 'Épinards frais en sachet',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 27,
      name: 'Chocolat noir Lindt',
      price: '3.90',
      quantity: '0.10',
      pricePerUnit: '39.00',
      barcode: '2583691470147',
      categoryId: 4,
      description: 'Chocolat noir 70% cacao',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 28,
      name: 'Miel d\'acacia',
      price: '6.80',
      quantity: '0.50',
      pricePerUnit: '13.60',
      barcode: '3691470258147',
      categoryId: 7,
      description: 'Miel d\'acacia naturel',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 29,
      name: 'Bœuf haché',
      price: '8.50',
      quantity: '0.40',
      pricePerUnit: '21.25',
      barcode: '1470369258147',
      categoryId: 5,
      description: 'Bœuf haché 15% MG',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 30,
      name: 'Thé Earl Grey',
      price: '4.20',
      quantity: '0.05',
      pricePerUnit: '84.00',
      barcode: '2580147369258',
      categoryId: 3,
      description: 'Thé Earl Grey 25 sachets',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 31,
      name: 'Avocat',
      price: '1.50',
      quantity: '0.20',
      pricePerUnit: '7.50',
      barcode: '3691470258369',
      categoryId: 1,
      description: 'Avocat Hass mûr',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 32,
      name: 'Salade iceberg',
      price: '1.80',
      quantity: '0.30',
      pricePerUnit: '6.00',
      barcode: '1470258369147',
      categoryId: 2,
      description: 'Salade iceberg fraîche',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 33,
      name: 'Cookies Pepito',
      price: '2.30',
      quantity: '0.20',
      pricePerUnit: '11.50',
      barcode: '2581470369147',
      categoryId: 4,
      description: 'Cookies tout chocolat',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 34,
      name: 'Quinoa',
      price: '4.90',
      quantity: '0.50',
      pricePerUnit: '9.80',
      barcode: '3690258147369',
      categoryId: 7,
      description: 'Quinoa blanc bio',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 35,
      name: 'Emmental râpé',
      price: '3.60',
      quantity: '0.20',
      pricePerUnit: '18.00',
      barcode: '1472583690147',
      categoryId: 5,
      description: 'Emmental râpé 200g',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 36,
      name: 'Muffins aux myrtilles',
      price: '3.20',
      quantity: '4.00',
      pricePerUnit: '0.80',
      barcode: '2583691470258',
      categoryId: 6,
      description: 'Muffins aux myrtilles x4',
      createdAt: new Date().toISOString(),
      unit: 'pc',
    },
    {
      id: 37,
      name: 'Ananas',
      price: '2.90',
      quantity: '1.20',
      pricePerUnit: '2.42',
      barcode: '3691470258147',
      categoryId: 1,
      description: 'Ananas Victoria',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 38,
      name: 'Poivrons rouges',
      price: '4.50',
      quantity: '0.40',
      pricePerUnit: '11.25',
      barcode: '1470369258147',
      categoryId: 2,
      description: 'Poivrons rouges bio',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 39,
      name: 'Champagne Mumm',
      price: '25.00',
      quantity: '0.75',
      pricePerUnit: '33.33',
      barcode: '2580369147258',
      categoryId: 3,
      description: 'Champagne brut 75cl',
      createdAt: new Date().toISOString(),
      unit: 'L',
    },
    {
      id: 40,
      name: 'Mentos',
      price: '1.20',
      quantity: '0.04',
      pricePerUnit: '30.00',
      barcode: '3691470258369',
      categoryId: 4,
      description: 'Bonbons Mentos menthe',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 41,
      name: 'Café moulu',
      price: '5.40',
      quantity: '0.25',
      pricePerUnit: '21.60',
      barcode: '1470258369147',
      categoryId: 3,
      description: 'Café moulu arabica',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 42,
      name: 'Beurre doux',
      price: '2.80',
      quantity: '0.25',
      pricePerUnit: '11.20',
      barcode: '2581470369258',
      categoryId: 5,
      description: 'Beurre doux 250g',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 43,
      name: 'Brioche tranchée',
      price: '2.60',
      quantity: '0.40',
      pricePerUnit: '6.50',
      barcode: '3690147258369',
      categoryId: 6,
      description: 'Brioche tranchée nature',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 44,
      name: 'Lentilles corail',
      price: '2.90',
      quantity: '0.50',
      pricePerUnit: '5.80',
      barcode: '1472580369147',
      categoryId: 7,
      description: 'Lentilles corail 500g',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
    {
      id: 45,
      name: 'Kiwi',
      price: '3.20',
      quantity: '0.60',
      pricePerUnit: '5.33',
      barcode: '2583691470369',
      categoryId: 1,
      description: 'Kiwi Zespri green',
      createdAt: new Date().toISOString(),
      unit: 'kg',
    },
  ]);

  const addCategory = (category) => {
    setCategories((prev) => [...prev, { ...category, id: Date.now() }]);
  };

  const addLabel = (label) => {
    setLabels((prev) => [
      ...prev,
      {
        ...label,
        id: Date.now(),
        categoryId: parseInt(label.categoryId),
        createdAt: new Date().toISOString(),
        barcode: label.barcode || generateBarcode(),
      },
    ]);
  };

  const deleteCategory = (id) => {
    setCategories((prev) => prev.filter((cat) => cat.id !== id));
    setLabels((prev) => prev.filter((label) => label.categoryId !== id));
  };

  const deleteLabel = (id) => {
    setLabels((prev) => prev.filter((label) => label.id !== id));
  };

  const updateCategory = (id, updatedCategory) => {
    setCategories((prev) =>
      prev.map((cat) => (cat.id === id ? { ...cat, ...updatedCategory } : cat))
    );
  };

  const updateLabel = (id, updatedLabel) => {
    setLabels((prev) =>
      prev.map((label) =>
        label.id === id
          ? {
              ...label,
              ...updatedLabel,
              categoryId: parseInt(updatedLabel.categoryId),
              price: parseFloat(updatedLabel.price).toFixed(2),
              quantity: parseFloat(updatedLabel.quantity).toFixed(2),
              pricePerUnit: updatedLabel.pricePerUnit,
              unit: updatedLabel.unit,
            }
          : label
      )
    );
  };

  const generateBarcode = () => {
    return Math.floor(Math.random() * 9000000000000) + 1000000000000;
  };

  const value = {
    categories,
    labels,
    addCategory,
    addLabel,
    deleteCategory,
    deleteLabel,
    updateCategory,
    updateLabel,
  };

  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
};